# ===========================
# ms-listing - DropCL
# ===========================
spring.application.name=ms-listing
server.port=8085

# ===========================
# Conexión MySQL (XAMPP)
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/dropCL_listing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA + Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===========================
# URLs de otros microservicios
# ===========================
ms.producto.url=http://localhost:8083
ms.inventario.url=http://localhost:8084
ms.usuario.url=http://localhost:8082

# ===========================
# Logs
# ===========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.dropcl.mslisting=INFO